services:
  format-check:
    build: .
    container_name: ChessApi_format-check
    command: bash -c "dotnet format --verify-no-changes"
  test:
    build: .
    container_name: ChessApi_test
    command: bash -c "dotnet test"
