services:

  backend:
    build:
      target: backend
    container_name: ChessApi_backend
    depends_on:
      - migrations
      - chess-db
    ports:
      - 8080:8080

  build:
    build:
      target: build
    container_name: ChessApi_build

  chess-db:
    image: postgres:latest
    container_name: ChessApi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ChessDB
    ports:
      - 5432:5432
    restart: always

  format-check:
    build:
      target: format-check
    container_name: ChessApi_format-check

  migrations:
    build:
      target: migrations
    container_name: ChessApi_migrations
    depends_on:
      - chess-db

  test:
    build:
      target: test
    container_name: ChessApi_test
